server {
    server_name landing.afanasevbots.ru;

    root /var/www/landing-tehspec;
    index index.html;

    include /etc/nginx/snippets/protechspec-security-headers.conf;

    location / {
        try_files $uri $uri/ =404;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/landing.afanasevbots.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/landing.afanasevbots.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = landing.afanasevbots.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;

    server_name landing.afanasevbots.ru;
    return 404; # managed by Certbot
}
